# Generated by Django 5.2 on 2025-04-22 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=150)),
                ('face_width', models.CharField(default='null', max_length=255)),
                ('face_height', models.CharField(default='null', max_length=255)),
                ('landmark', models.CharField(default='null', max_length=255)),
                ('smilingProbability', models.CharField(default='null', max_length=255)),
                ('LeftEyeOpenProbability', models.CharField(default='null', max_length=255)),
                ('rightEyeOpenProbability', models.CharField(default='null', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='face_images/')),
                ('face', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came', models.DateTimeField()),
                ('went', models.DateTimeField()),
                ('went_lunch', models.DateTimeField()),
                ('came_lunch', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
