# Generated by Django 5.2 on 2025-04-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('face_width', models.CharField(max_length=255)),
                ('face_height', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('smilingProbability', models.CharField(max_length=255)),
                ('LeftEyeOpenProbability', models.CharField(max_length=255)),
                ('rightEyeOpenProbability', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='face_images/')),
                ('face', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(max_length=50)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('start_word_at', models.DateTimeField(blank=True, null=True)),
                ('end_word_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='face_images/')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('face_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.face')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came', models.DateTimeField()),
                ('went', models.DateTimeField()),
                ('went_lunch', models.DateTimeField()),
                ('came_lunch', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.staff')),
            ],
        ),
    ]
